improved error handling around kubectl calls

diff --git a/server/plugins/check_ceph b/server/plugins/check_ceph
--- a/server/plugins/check_ceph
+++ b/server/plugins/check_ceph
@@ -61,7 +61,15 @@ done
 TOKEN=$(cat /run/secrets/kubernetes.io/serviceaccount/token)
 KUBECTL="kubectl --server $APISERVER --token $TOKEN --certificate-authority=/run/secrets/kubernetes.io/serviceaccount/ca.crt"
 
-STATUS=$( $KUBECTL -n $NAMESPACE exec rook-tools ceph status )
+STATUS=$( $KUBECTL -n $NAMESPACE exec rook-tools ceph status 2>&1 )
+if [ $? -ne 0 ]; then
+        echo "[ERR] failed to connect to ceph: $STATUS"
+        exit $STATE_CRITICAL
+fi
+if [ "$STATUS" == "" ]; then
+        echo "[UNKNOWN] no answer"
+        exit $STATE_UNKNOWN
+fi
 
 HEALTH=$( echo "$STATUS" | head -n 3 | tail -n 1 | awk '{print $4}' )
 if [ "$STATUS" == "HEALTH_ERR" ]; then
diff --git a/server/plugins/check_kubernetes b/server/plugins/check_kubernetes
--- a/server/plugins/check_kubernetes
+++ b/server/plugins/check_kubernetes
@@ -47,11 +47,14 @@ done
 TOKEN=$(cat /run/secrets/kubernetes.io/serviceaccount/token)
 KUBECTL="kubectl --server $APISERVER --token $TOKEN --certificate-authority=/run/secrets/kubernetes.io/serviceaccount/ca.crt"
 
-STATUS=$( $KUBECTL get cs --no-headers=true )
-
-if [ "$STATUS" == "" ]; then
-        echo "[CRIT] no answer"
+STATUS=$( $KUBECTL get cs --no-headers=true 2>&1 )
+if [ $? -ne 0 ]; then
+        echo "[ERR] failed to connect to ceph: $STATUS"
         exit $STATE_CRITICAL
+fi
+if [ "$STATUS" == "" ]; then
+        echo "[UNKNOWN] no answer"
+        exit $STATE_UNKNOWN
 fi
 
 HEALTH=$(      echo "$STATUS" | grep etcd-0             | awk -F ' ' '{print $2}' )
diff --git a/server/plugins/check_pods b/server/plugins/check_pods
--- a/server/plugins/check_pods
+++ b/server/plugins/check_pods
@@ -62,7 +62,11 @@ TOKEN=$(cat /run/secrets/kubernetes.io/serviceaccount/token)
 KUBECTL="kubectl --server $APISERVER --token $TOKEN --certificate-authority=/run/secrets/kubernetes.io/serviceaccount/ca.crt"
 
 
-STATUS=$( $KUBECTL version )
+STATUS=$( $KUBECTL version 2>&1 )
+if [ $? -ne 0 ]; then
+        echo "[ERR] failed to connect to ceph: $STATUS"
+        exit $STATE_CRITICAL
+fi
 if [ "$STATUS" == "" ]; then
         echo "[UNKNOWN] no answer"
         exit $STATE_UNKNOWN
